# Generated by Django 4.1.5 on 2023-01-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_home_delete_thing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='zip',
            field=models.IntegerField(default=0),
        ),
    ]
